### ISSUE TITLE
Comma instead of space?

### ISSUE THREAD

**Issue by kevinawalsh** [BorysLevytskyi/BitwiseCmd#12] opened 2020-01-27 01:22 UTC
Consider using comma in place of space, as it might be less confusing. Currently...
Input: 1 2 3 4
This prints out four numbers in binary, which is reasonable. But...
Input: 1 2 3 4|1
This prints out the result of (1234 ) | 1, which is rather unexpected, since numbers can't usually have spaces in them, and it seems like it should have printed four numbers, with the last one being the result of 4|1.

If using comma (or semicolon or something), these examples would be clear:
Input: 1, 2, 3, 4 -- prints four numbers
Input: 1, 2, 3, 4|1 -- prints out four numbers, the last being the result of 4|1
Input: 1&1, 2&1, 3&1, 4&1 -- print out four results
etc.

**Comment by BorysLevytskyi** [comment] 2023-05-04 11:37
Hi, Kevin. Thank you for taking the time to write about this. It was a personal preference of mine to use spaces. Also, typing a space takes one key whereas typing a comma requires two keys.  But I guess this is just a matter of individual preference. BitwiseCmd is now in maintenance mode and I don't have plans to work on it anymore as of now. This might change later. For now, I'm closing this issue as By Design. I hope this is not too big of a problem for everybody :)

**Closed by BorysLevytskyi** 2023-05-04 11:37 UTC
